# Site settings
title: Alessandro Vullo
# twitter_username: rob_hinds
name: Alessandro Vullo

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/avullo
 - title: LinkedIn
   url: https://www.linkedin.com/in/alessandro-vullo-12157928

#Any buzzword skills you want to include
skills:
 - Machine Learning
 - Data Science
 - C++
 - Python
 - Perl
 - SQL
 - REST

#Work experience is required
roles:
 - title: Software Engineer
   start: 2013
   end: Ongoing
   employer: European Bioinformatics Institute
   description: I work as a Software Engineer in the Ensembl group, where I collaboratively develop and maintain the core/REST APIs and various data intensive pipelines used in the release cycle.
 - title: Project Manager
   start: 2016
   end: 2017
   employer: European Bioinformatics Institute
   description: I have supervised the migration of the hardware and software infrastructure of the Ensembl team from the Sanger Institute to the European Bioinformatics Institute
 - title: Data Scientist
   start: 2012
   end: 2013
   employer: Self employed
   description: I run statistical analyses and machine learning based predictive modeling using biometric data from samples of pheasants in a game reserve. The project was funded by the regional govenment of Tuscany in Italy.  
 - title: Bioinformatics Engineer
   start: 2010
   end: 2013
   employer: European Bioinformatics Institute
   description: I was the lead software developer of Microme, a EU-funded project involving several institutes in Europe to develop a large scale infrastructure for the storage and processing of computational models of microbial species. 
 - title: Freelance Web Developer
   start: 2008
   end: 2010
   employer: Self employed
   description: I designed, implemented and maintained various commercial web sites.
 - title: Research Associate
   start: 2007
   end: 2009
   employer: Complex and Adaptive Systems Lab, University College Dublin
   description: I researched and developed machine learning models for protein disorder prediction and cheminformatics. I have also applied machine learning techniques to study protein pseudo-folding pathways.

#Education is required
education:
 - level: Doctor of Philosophy (Ph.D)
   date: 2004
   subject: Machine Learning and Bioinformatics
   school: Department of Systems and Computer Science, University of Florence (Italy)
 - level: Master of Science (M.Sc.)
   date: 2000
   subject: Computer Engineering
   school: University of Florence (Italy)

#List of interesting Github repo/projects to include - optional
github:
 - avullo/recursive-neural-networks
 - avullo/BIOHMMs
 - Ensembl/trackhub-registry
 - Ensembl/ensembl
 - Ensembl/ensembl-rest
 - Ensembl/ensembl-xs