# Site settings
title: Alessandro Vullo
# twitter_username: rob_hinds
name: Alessandro Vullo

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/avullo
 - title: LinkedIn
   url: https://www.linkedin.com/in/alessandro-vullo-12157928
 - title: Software
   url: software.html
 - title: Online/Web Services
   url: services.html
 - title: Publications
   url: publications.html

#Any buzzword skills you want to include
skills:
 - Machine Learning
 - Data Science
 - Data Mining
 - Bioinformatics
 - C++
 - Python
 - R
 - Perl
 - REST
 - SQL
 - MySQL
 - Elasticsearch
 - Design Patterns
 - Test-driven Development
 - Continuous Integration

#Work experience is required
roles:
 - title: Software Engineer
   start: 2013
   end: Ongoing
   employer: European Bioinformatics Institute
   description: I work as a software engineer for <a href="http://www.ensembl.org" target="_blank">Ensembl</a>, where I collaboratively develop and maintain the core/REST APIs and various data intensive pipelines used in the release cycle. I have developed and currently maintain the <a href="https://www.trackhubregistry.org" target="_blank">Trackhub Registry</a>, a global, centralised collection of publicly accessible track hubs published by researchers worldwide and directly loadable into popular genome browsers. As part of my work, I co-develop and maintain <a href="https://github.com/Ensembl/Bio-DB-HTS">Bio::DB::HTS</a>, a popular Perl interface to the the <a href="http://www.htslib.org">HTSlib</a> library to access high-throughput sequencing data . I am also lecturing at the Ensembl API workshops at the European Bioinformatics Institute and the University of Cambridge and give presentations about our work around the UK.
 - title: Project Manager
   start: 2016
   end: 2017
   employer: European Bioinformatics Institute
   description: I have supervised the <a href="https://avullo.github.io/ensembl-migration-pm" target="_blank">migration</a> of the hardware and software infrastructure of the Ensembl team from the Sanger Institute to the European Bioinformatics Institute
 - title: Data Scientist
   start: 2012
   end: 2013
   employer: Self employed
   description: Project "Pheasant", funded by the regional government of Tuscany (Italy). I run statistical analyses and Machine Learning based predictive modeling using biometric data from samples of pheasants in the ZRC ATC 19 governmental game reserve.   
 - title: Bioinformatics Engineer
   start: 2010
   end: 2013
   employer: European Bioinformatics Institute
   description: I was the lead software developer of <a href="http://www.microme.eu" target="_blank">Microme</a>, a EU-funded project involving several institutes in Europe to develop a large scale infrastructure for the storage and processing of computational models of microbial species. 
 - title: Freelance Web Developer
   start: 2008
   end: 2010
   employer: Self employed
   description: I designed, implemented and maintained various commercial web sites.
 - title: Research Associate
   start: 2007
   end: 2009
   employer: Complex and Adaptive Systems Lab, University College Dublin
   description: I researched and developed Machine Learning models for protein disorder prediction and cheminformatics. I have also applied machine learning techniques to study protein pseudo-folding pathways.
 - title: Post-doctoral fellow
   start: 2004
   end: 2007
   employer: School of Computer Science and Informatics, University College Dublin
   description: Design and implementaton of Machine Learning models to automatically interpret and annotate molecular biology data on a very large scale. I have developed the interface, server-side scripts and main application of various <a href="software.html#distill">tools and servers for protein structure/disorder prediction</a> (Distill). I was also responsible for the set up and administration of the computational cluster of the AmMBIO group.
 - title: Visiting Researcher
   start: May 2003
   end: Sep 2003
   employer: University of California at Irvine
   description: In partnership with the School of Information and Computer Sciences and the Institute for Genomics and Bioinformatics to further explore the potential of new deterministic graphical models based on Recursive Neural Networks in protein structure prediction problems.
 - title: Co-Director, Full-stack Web Developer, Linux System Administrator
   start: 1997
   end: 2001
   employer: NewNet Informatics Ltd
   description: I founded a small start up together with friends and colleagues from university. The company worked as an Internet Service Provider and provided customised web applications and e-commerce solutions based on PHP and Javascript.
 - title: Post graduate Researcher
   start: 1999
   end: 2000
   employer: Department of Systems and Computer Science, University of Florence (Italy)
   description: Project <a href="http://www.dcc.ac.uk/resources/external/metae-metadata-engine-project" target="_blank">META-E The Metadata Engine Project</a>, IST Programme, Area "Digital heritage and cultural content", EU Grant IST-1999-20021. Model design and development of probabilistic graphical models for document classification (text categorization). I have employed the C++ framework developed during my master thesis to train and test HMMs to capture the sequential structure of certain document spaces, and modeling the emission distribution with either Naive Bayes or Hidden Tree Markov models (HTMMs).


#Education is required
education:
 - level: Doctor of Philosophy (Ph.D)
   date: 2004
   subject: Machine Learning and Bioinformatics
   school: Department of Systems and Computer Science, University of Florence (Italy)
 - level: Master of Science (M.Sc.)
   date: 2000
   subject: Computer Engineering
   school: University of Florence (Italy)

#List of interesting Github repo/projects to include - optional
github:
 - avullo/recursive-neural-networks
 - avullo/BIOHMMs
 - Ensembl/trackhub-registry
 - Ensembl/ensembl
 - Ensembl/ensembl-rest
 - Ensembl/ensembl-xs