# Site settings
title: Alessandro Vullo
twitter_username: 
name: Alessandro Vullo

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/avullo
 - title: LinkedIn
   url: https://www.linkedin.com/in/alessandro-vullo-12157928

#Any buzzword skills you want to include
skills:
 - Machine Learning
 - Data Science
 - C++
 - Python
 - Perl
 - SQL
 - REST

#Work experience is required
roles:
 - title: Software Engineer
   start: 2013
   end: Ongoing
   employer: European Bioinformatics Institute
   description: 
 - title: Project Manager
   start: 2016
   end: 2017
   employer: European Bioinformatics Institute
   description: 
 - title: Bioinformatician
   start: 2010
   end: 2013
   employer: European Bioinformatics Institute
   description: 

#Education is required
education:
 - level: Ph.D
   date: 2004
   subject: Machine Learning and Bioinformatics
   school: Department of Systems and Computer Science, University of Florence (Italy)
 - level: Master of Science (M.Sc.)
   date: 2000
   subject: Computer Engineering
   school: University of Florence (Italy)

#List of interesting Github repo/projects to include - optional
github:
 - Ensembl/ensembl
 - Ensembl/ensembl-rest
 - Ensembl/ensembl-xs
 - avullo/recursive-neural-networks
 - avullo/BIOHMMs
